// Generates lib/ide/terminal/shell_integration/shell_integration_scripts.dart
// from VS Code's shell integration scripts, unchanged.
//
// Run with a checkout of VS Code at the port's revision (a sparse checkout of
// src/vs/workbench/contrib/terminal/common/scripts is enough):
//   dart run tool/generate_shell_integration_scripts.dart <vscode checkout>
// then `dart format` the generated file.

import 'dart:convert';
import 'dart:io';

/// The revision the terminal is ported from.
const _revision = '6a598d4a13031703d483d103c1d934a36ad27971';

const _scriptsPath = 'src/vs/workbench/contrib/terminal/common/scripts';

/// The scripts VS Code's getShellIntegrationInjection points shells at.
const _scripts = [
  'shellIntegration-bash.sh',
  'shellIntegration-env.zsh',
  'shellIntegration-login.zsh',
  'shellIntegration-profile.zsh',
  'shellIntegration-rc.zsh',
  'shellIntegration.fish',
  'shellIntegration.ps1',
];

const _output =
    'lib/ide/terminal/shell_integration/shell_integration_scripts.dart';

Future<void> main(List<String> arguments) async {
  if (arguments.length != 1) {
    stderr.writeln(
      'Usage: dart run tool/generate_shell_integration_scripts.dart '
      '<vscode checkout>',
    );
    exit(64);
  }
  final checkout = arguments.single;
  final head = await _git(checkout, ['rev-parse', 'HEAD']);
  if (head != _revision) {
    stderr.writeln('The checkout is at $head, not $_revision.');
    exit(1);
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_shell_integration_scripts.dart:')
    ..writeln("// VS Code's shell integration scripts, byte for byte, from")
    ..writeln('// $_revision')
    ..writeln('// $_scriptsPath')
    ..writeln('// (git blob ids below). Do not edit: run the tool again.')
    ..writeln('//')
    ..writeln('// Copyright (c) Microsoft Corporation. All rights reserved.')
    ..writeln(
      '// Licensed under the MIT License (each script keeps its header).',
    )
    ..writeln()
    ..writeln(
      "/// VS Code's scripts by file name, as getShellIntegrationInjection",
    )
    ..writeln('/// finds them in its scripts folder.')
    ..writeln('const shellIntegrationScripts = <String, String>{');
  for (final name in _scripts) {
    final path = '$_scriptsPath/$name';
    final bytes = await File('$checkout/$path').readAsBytes();
    final text = utf8.decode(bytes);
    if (!_sameBytes(utf8.encode(text), bytes)) {
      throw StateError('$name does not round-trip through UTF-8');
    }
    final blob = await _git(checkout, ['rev-parse', 'HEAD:$path']);
    out
      ..writeln('  // $blob')
      ..writeln("  '$name': ${_literal(name, text)},");
  }
  out.writeln('};');
  await File(_output).writeAsString(out.toString());
  stdout.writeln('Wrote $_output');
}

/// [text] as a raw multi-line string literal, which keeps every character.
String _literal(String name, String text) {
  // A raw multi-line string drops its first line when that line is blank.
  if (RegExp(r'^[ \t]*\r?\n').hasMatch(text)) {
    throw StateError('$name starts with a blank line');
  }
  for (final quote in const ["'''", '"""']) {
    if (!text.contains(quote) && !text.endsWith(quote[0])) {
      return 'r$quote$text$quote';
    }
  }
  throw StateError('$name cannot be a raw string literal');
}

Future<String> _git(String checkout, List<String> arguments) async {
  final result = await Process.run('git', ['-C', checkout, ...arguments]);
  if (result.exitCode != 0) {
    throw StateError('git ${arguments.join(' ')}: ${result.stderr}');
  }
  return (result.stdout as String).trim();
}

bool _sameBytes(List<int> a, List<int> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
