#!/usr/bin/env node
// Bundles Codicons, VS Code's icon font, as the pinned VS Code uses it, for
// the Fast Ide's icons.
//
//   npm pack @vscode/codicons@0.0.46-40 && tar xzf vscode-codicons-*.tgz
//   node tool/generate_codicons.mjs <vscode-checkout> package \
//     assets/codicons lib/theme/codicons.dart
//
// The VS Code checkout must be at 6a598d4a13031703d483d103c1d934a36ad27971,
// whose package-lock.json pins the codicons package; the names come from its
// src/vs/base/common/{codiconsLibrary,codicons}.ts (the derived names too).
// Writes <output-dir>/codicon.ttf and LICENSE (CC-BY-4.0, with attribution),
// and the Dart constants.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const vscodeCommit = '6a598d4a13031703d483d103c1d934a36ad27971';

const [vscode, source, output, dart] = process.argv.slice(2);
if (!vscode || !source || !output || !dart) {
  console.error(
    'usage: generate_codicons.mjs <vscode-checkout> <package-dir> ' +
      '<output-dir> <codicons.dart>',
  );
  process.exit(64);
}

const head = execFileSync('git', ['-C', vscode, 'rev-parse', 'HEAD'], {
  encoding: 'utf8',
}).trim();
if (head !== vscodeCommit) {
  console.error(`VS Code checkout is at ${head}, not ${vscodeCommit}`);
  process.exit(65);
}
const lock = JSON.parse(
  execFileSync('git', ['-C', vscode, 'show', 'HEAD:package-lock.json'], {
    encoding: 'utf8',
    maxBuffer: 64 << 20,
  }),
);
const pinned = lock.packages['node_modules/@vscode/codicons'].version;
const pkg = JSON.parse(
  fs.readFileSync(path.join(source, 'package.json'), 'utf8'),
);
if (pkg.name !== '@vscode/codicons' || pkg.version !== pinned) {
  console.error(`expected @vscode/codicons@${pinned}, got ${pkg.name}@${pkg.version}`);
  process.exit(65);
}

// `camelName: register('kebab-name', 0xea60)` in the library; derived icons
// name another icon instead of a code point.
const common = path.join(vscode, 'src', 'vs', 'base', 'common');
const read = (file) => fs.readFileSync(path.join(common, file), 'utf8');
const pattern = /^\s*(\w+): register\('([\w-]+)', (0x[0-9a-f]+|'[\w-]+')\)/gm;
const byName = new Map();
const icons = [];
for (const file of ['codiconsLibrary.ts', 'codicons.ts']) {
  for (const [, id, name, value] of read(file).matchAll(pattern)) {
    const code = value.startsWith('0x')
      ? Number.parseInt(value, 16)
      : byName.get(value.slice(1, -1));
    if (code === undefined) throw new Error(`${name}: unknown ${value}`);
    byName.set(name, code);
    if (!icons.some((icon) => icon.id === id)) icons.push({ id, name, code });
  }
}

fs.mkdirSync(output, { recursive: true });
fs.copyFileSync(
  path.join(source, 'dist', 'codicon.ttf'),
  path.join(output, 'codicon.ttf'),
);
fs.writeFileSync(
  path.join(output, 'LICENSE'),
  `codicon.ttf is from ${pkg.name}@${pkg.version} ` +
    '(https://github.com/microsoft/vscode-codicons), Copyright (c) ' +
    'Microsoft Corporation, licensed under the Creative Commons ' +
    'Attribution 4.0 International license below. It is unmodified.\n\n' +
    fs.readFileSync(path.join(source, 'LICENSE'), 'utf8').replace(/^﻿/, ''),
);

const hex = (code) => `0x${code.toString(16)}`;
const lines = [
  '// Generated by tool/generate_codicons.mjs from VS Code',
  `// ${vscodeCommit} (src/vs/base/common/codiconsLibrary.ts and`,
  `// codicons.ts) and ${pkg.name}@${pkg.version}. Do not edit.`,
  '//',
  '// The font is CC-BY-4.0: see assets/codicons/LICENSE.',
  '',
  "import 'package:flutter/widgets.dart';",
  '',
  "/// VS Code's icons, by the names VS Code gives them (`Codicons.files` is",
  '/// `$(files)`).',
  'abstract final class Codicons {',
  "  static const fontFamily = 'codicon';",
  '',
  ...icons.flatMap(({ id, name, code }) => [
    `  /// \`${name}\``,
    `  static const IconData ${id} = IconData(${hex(code)}, fontFamily: fontFamily);`,
  ]),
  '',
  '  /// Every icon by its VS Code name (`symbol-class`).',
  '  static const Map<String, IconData> byName = {',
  // A name registered twice is the later one's, as VS Code's registry has it.
  ...[...new Map(icons.map(({ id, name }) => [name, id]))].map(
    ([name, id]) => `    '${name}': ${id},`,
  ),
  '  };',
  '}',
  '',
];
fs.writeFileSync(dart, lines.join('\n'));
console.log(`${icons.length} icons from ${pkg.name}@${pkg.version}`);
