import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:bao_editor/monaco/vs/editor/common/core/position.dart';
import 'package:bao_editor/monaco/vs/editor/common/core/range.dart';
import 'package:bao_editor/monaco/vs/editor/common/core/selection.dart';

Range rangeOf(List<dynamic> coordinates) => Range(
  coordinates[0] as int,
  coordinates[1] as int,
  coordinates[2] as int,
  coordinates[3] as int,
);

void main() {
  // Generated by running the pinned TypeScript, not a second Dart algorithm.
  final fixture = jsonDecode(
    File('test/fixtures/monaco/core.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  test('fixtures identify the pinned upstream revision', () {
    expect(fixture['revision'], '6a598d4a13031703d483d103c1d934a36ad27971');
  });

  test('Position matches TypeScript fixtures including signed comparisons', () {
    for (final item in fixture['position'] as List) {
      final input = item['input'] as List;
      final a = Position(input[0] as int, input[1] as int);
      final b = Position(input[2] as int, input[3] as int);
      expect(a.equals(b), item['equals'], reason: '$input');
      expect(a.isBefore(b), item['before'], reason: '$input');
      expect(a.isBeforeOrEqual(b), item['beforeOrEqual'], reason: '$input');
      expect(Position.compare(a, b), item['compare'], reason: '$input');
      expect(a.delta(-2, 3).toJson(), item['delta'], reason: '$input');
      expect(a.withPosition(b.lineNumber).toJson(), item['withPosition']);
      expect(a.toString(), item['display']);
    }
  });

  test('Range operations match TypeScript fixtures', () {
    for (final item in fixture['range'] as List) {
      final a = rangeOf(item['input'] as List);
      final b = rangeOf(item['other'] as List);
      final reason = '${item['input']} / ${item['other']}';
      expect(a.toJson(), item['normalized'], reason: reason);
      expect(a.isEmpty(), item['empty'], reason: reason);
      expect(a.containsRange(b), item['contains'], reason: reason);
      expect(a.strictContainsRange(b), item['strictContains'], reason: reason);
      expect(a.plusRange(b).toJson(), item['union'], reason: reason);
      expect(
        a.intersectRanges(b)?.toJson(),
        item['intersection'],
        reason: reason,
      );
      expect(
        Range.areIntersectingOrTouching(a, b),
        item['touching'],
        reason: reason,
      );
      expect(Range.areIntersecting(a, b), item['intersecting'], reason: reason);
      expect(
        Range.areOnlyIntersecting(a, b),
        item['onlyIntersecting'],
        reason: reason,
      );
      expect(
        Range.compareRangesUsingStarts(a, b),
        item['compareStarts'],
        reason: reason,
      );
      expect(
        Range.compareRangesUsingEnds(a, b),
        item['compareEnds'],
        reason: reason,
      );
      expect(a.toString(), item['display'], reason: reason);
    }
  });

  test('Selection direction and endpoint edits match TypeScript fixtures', () {
    for (final item in fixture['selection'] as List) {
      final input = item['input'] as List;
      final a = Selection(
        input[0] as int,
        input[1] as int,
        input[2] as int,
        input[3] as int,
      );
      expect(a.toJson(), item['value'], reason: '$input');
      expect(a.getDirection().index, item['direction'], reason: '$input');
      expect(
        a.setStartPosition(2, 3).toJson(),
        item['changeStart'],
        reason: '$input',
      );
      expect(
        a.setEndPosition(4, 5).toJson(),
        item['changeEnd'],
        reason: '$input',
      );
      expect(
        Selection.fromRange(a, SelectionDirection.rtl).toJson(),
        item['fromRangeReverse'],
        reason: '$input',
      );
      expect(a.toString(), item['display'], reason: '$input');
    }
  });
}
