// VS Code's own settings (schemas and defaults) as the desktop workbench of
// the pinned upstream registers them, read from
// assets/exthost/core_configuration.json (generated by
// tool/generate_core_configuration.mjs), for one platform.

import 'dart:convert';
import 'dart:io';

import 'package:flutter/services.dart';

import 'configuration_model.dart';
import 'configuration_registry.dart';

const coreConfigurationAsset = 'assets/exthost/core_configuration.json';

/// The core settings of one platform: what [ConfigurationRegistry] takes as
/// `core` and `coreDefaults`.
final class CoreConfiguration {
  const CoreConfiguration({
    required this.upstreamCommit,
    required this.properties,
    required this.defaults,
  });

  /// From the generated JSON, for [platform] (`darwin`, `win32`, `linux`).
  factory CoreConfiguration.fromJson(
    Map<String, Object?> json, {
    required String platform,
  }) {
    Map<String, Object?> section(String name) =>
        ((json[name] as Map?)?[platform] as Map?)?.cast<String, Object?>() ??
        const {};
    final platformDefaults = section('platformDefaults');
    final platformSchemas = section('platformSchemas');
    final properties = <String, Map<String, Object?>>{};
    for (final MapEntry(:key, :value)
        in (json['properties']! as Map).cast<String, Object?>().entries) {
      final schema = Map<String, Object?>.of((value! as Map).cast());
      final platforms = schema.remove('platforms');
      if (platforms is List && !platforms.contains(platform)) continue;
      final overrides = platformSchemas[key];
      if (overrides is Map) schema.addAll(overrides.cast());
      if (platformDefaults.containsKey(key)) {
        schema['default'] = platformDefaults[key];
      }
      properties[key] = schema;
    }

    // Core's `registerDefaultConfigurations`, then the declarative built-in
    // extensions' `configurationDefaults` (`[lang]` objects merged).
    final defaults = <String, Object?>{};
    void add(Object? entries) {
      if (entries is! Map) return;
      for (final MapEntry(:key, :value)
          in entries.cast<String, Object?>().entries) {
        final existing = defaults[key];
        defaults[key] = isOverrideKey(key) && value is Map && existing is Map
            ? {
                ...existing.cast<String, Object?>(),
                ...value.cast<String, Object?>(),
              }
            : value;
      }
    }

    add(json['configurationDefaults']);
    final builtin = json['builtinExtensionDefaults'];
    if (builtin is Map) builtin.values.forEach(add);

    return CoreConfiguration(
      upstreamCommit: json['upstreamCommit'] as String? ?? '',
      properties: properties,
      defaults: defaults,
    );
  }

  /// Reads [coreConfigurationAsset] for the platform this runs on.
  static Future<CoreConfiguration> load({
    AssetBundle? bundle,
    String? platform,
  }) async {
    final text = await (bundle ?? rootBundle).loadString(
      coreConfigurationAsset,
      cache: false,
    );
    return CoreConfiguration.fromJson(
      (jsonDecode(text) as Map).cast(),
      platform: platform ?? currentPlatform,
    );
  }

  /// VS Code's name of the platform this runs on.
  static String get currentPlatform => Platform.isMacOS
      ? 'darwin'
      : Platform.isWindows
      ? 'win32'
      : 'linux';

  final String upstreamCommit;

  /// Key → schema (with `scope` a [ConfigurationScope] number, `title` and
  /// `groupOrder` the registering node's title and order).
  final Map<String, Map<String, Object?>> properties;

  /// `configurationDefaults` registered by VS Code itself.
  final Map<String, Object?> defaults;

  /// A registry of these settings and [extensions]' (`IExtensionDescription`s).
  ConfigurationRegistry registry({
    List<Map<String, Object?>> extensions = const [],
  }) => ConfigurationRegistry(
    core: properties,
    coreDefaults: defaults,
    extensions: extensions,
  );
}
