// The app's strings (lib/l10n/app_*.arb, generated by `flutter gen-l10n`).
//
// Widgets read them with `context.l10n`, which falls back to English where
// no AppLocalizations is in scope (a bare MaterialApp in a widget test, a
// dialog built above the app's Localizations).
import 'package:flutter/widgets.dart';

import 'app_localizations.dart';
import 'app_localizations_en.dart';

export 'app_localizations.dart';

/// The English strings: the template's, and what [AppLocalizationsContext.l10n]
/// falls back to.
final AppLocalizations englishLocalizations = AppLocalizationsEn();

extension AppLocalizationsContext on BuildContext {
  /// The strings of the locale in scope; English when there is none.
  AppLocalizations get l10n =>
      AppLocalizations.of(this) ?? englishLocalizations;
}
